[2025-05-05T23:59:14.328+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T23:59:02.034475+00:00 [queued]>
[2025-05-05T23:59:14.361+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T23:59:02.034475+00:00 [queued]>
[2025-05-05T23:59:14.363+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-05T23:59:14.412+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): entrenar_modelo> on 2025-05-05 23:59:02.034475+00:00
[2025-05-05T23:59:14.469+0000] {standard_task_runner.py:57} INFO - Started process 718 to run task
[2025-05-05T23:59:14.486+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Train_Model', 'entrenar_modelo', 'manual__2025-05-05T23:59:02.034475+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/Train_Data.py', '--cfg-path', '/tmp/tmp4jshb3u5']
[2025-05-05T23:59:14.497+0000] {standard_task_runner.py:85} INFO - Job 145: Subtask entrenar_modelo
[2025-05-05T23:59:14.653+0000] {task_command.py:416} INFO - Running <TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T23:59:02.034475+00:00 [running]> on host airflow-worker-5c47d7d789-mw9hk
[2025-05-05T23:59:14.831+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Train_Model' AIRFLOW_CTX_TASK_ID='entrenar_modelo' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T23:59:02.034475+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T23:59:02.034475+00:00'
[2025-05-05T23:59:20.529+0000] {logging_mixin.py:154} INFO - Filas le√≠das: 101766
[2025-05-05T23:59:28.384+0000] {logging_mixin.py:154} WARNING - 2025/05/05 23:59:28 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-05T23:59:28.482+0000] {logging_mixin.py:154} INFO - Fitting 3 folds for each of 8 candidates, totalling 24 fits
[2025-05-05T23:59:31.430+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   2.7s
[2025-05-05T23:59:33.163+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   1.7s
[2025-05-05T23:59:34.810+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   1.6s
[2025-05-05T23:59:40.224+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   5.4s
[2025-05-05T23:59:44.416+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   4.2s
[2025-05-05T23:59:48.811+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   4.4s
[2025-05-05T23:59:51.954+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   3.1s
[2025-05-05T23:59:55.782+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   3.8s
[2025-05-05T23:59:59.176+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   3.4s
[2025-05-06T00:00:07.587+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   8.4s
[2025-05-06T00:00:15.553+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   8.0s
[2025-05-06T00:00:24.648+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   9.1s
[2025-05-06T00:00:30.185+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   5.5s
[2025-05-06T00:00:34.236+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   4.1s
[2025-05-06T00:00:37.937+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   3.7s
[2025-05-06T00:00:47.470+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   9.5s
[2025-05-06T00:00:58.671+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=  11.2s
[2025-05-06T00:01:08.244+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   9.6s
[2025-05-06T00:01:14.385+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   6.1s
[2025-05-06T00:01:19.533+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   5.1s
[2025-05-06T00:01:26.471+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   6.9s
[2025-05-06T00:01:45.642+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=  19.2s
[2025-05-06T00:01:59.625+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=  14.0s
[2025-05-06T00:02:14.335+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=  14.7s
[2025-05-06T00:03:30.750+0000] {logging_mixin.py:154} WARNING - 2025/05/06 00:03:30 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-05-06T00:03:31.980+0000] {credentials.py:1124} INFO - Found credentials in environment variables.
[2025-05-06T00:03:35.999+0000] {logging_mixin.py:154} INFO - Modelo entrenado con par√°metros: {'max_depth': 10, 'max_features': 10, 'n_estimators': 100}
[2025-05-06T00:03:36.546+0000] {logging_mixin.py:154} WARNING - Registered model 'RandomForestModel' already exists. Creating a new version of this model...
[2025-05-06T00:03:36.739+0000] {logging_mixin.py:154} WARNING - 2025/05/06 00:03:36 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: RandomForestModel, version 7
[2025-05-06T00:03:36.740+0000] {logging_mixin.py:154} WARNING - Created version '7' of model 'RandomForestModel'.
[2025-05-06T00:03:36.748+0000] {warnings.py:109} WARNING - /opt/airflow/dags/Train_Data.py:81: FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  client.transition_model_version_stage(

[2025-05-06T00:03:36.955+0000] {logging_mixin.py:154} INFO - üèÉ View run rf_diabetes_all_varchar at: http://10.152.183.196:5000/#/experiments/1/runs/1dfbfe7d1072473788fe8df4719f5d33
[2025-05-06T00:03:36.955+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-06T00:03:37.794+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-06T00:03:37.868+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Train_Model, task_id=entrenar_modelo, execution_date=20250505T235902, start_date=20250505T235914, end_date=20250506T000337
[2025-05-06T00:03:38.277+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-06T00:03:38.382+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
